### ISSUE TITLE
Angular RC 1 support

### ISSUE THREAD

**Issue by aaweb** [vladotesanovic/ngSemantic#18]
Thanks for the great project!

Now that RC 1 it out, the Angular team changed the import to `@angular/...` instead of `angular2/...`. Would be great if ngSemantic could be updated too.

Cheers,
Andy

**Comment by TerryMooreII** [comment]
+1

**Comment by TerryMooreII** [comment]
I was able to migrate the ng-semantic components to angular 2 rc with relative ease.  I had to copy the ng-semantic directory to my project in order to build it but things did work.
  
I was not however able to migrate the documentation to rc due to some dependant packages that have not been updated to angular 2 rc.  This is why I had to copy the ng-semantic folder to my project instead of running the ng-semantic node bundle scripts.  I will keep an eye on those dependencies or keep looking for workarounds in order to get this project up to the latest version of angular 2.  

I can push my branch later tonight if anyone is interested in hacking away on it.

**Comment by vladotesanovic** [comment]
Yes, please submit it as PR. 

I am going to update this project to rc.1 tonight, i didn't work on it last month, but i am going to push it harder in next few days / weeks.

**Comment by TerryMooreII** [comment]
I dont want to submit a pull request because this branch isnt fully working....yet.  You can check out my current progress on this branch https://github.com/TerryMooreII/ngSemantic/tree/angular2-migration

Bundle now runs successfully
```
$ tsc && node bundle.js && cp ./bundles/ng-semantic.js ./demo/vendor
Build complete.
Minified build complete.
```

But npm run demo:build fails with this message
```
$ npm run demo:build

> ng-semantic@1.0.21 demo:build /Users/terrymooreii/code/github/ngSemantic
> rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo

node_modules/ng2-src-directive/src/sourcable.d.ts(3,21): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(6,21): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(9,19): error TS7006: Parameter 'any' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(12,22): error TS7006: Parameter 'Response' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(15,22): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(16,22): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(17,20): error TS7006: Parameter 'any' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/sourcable.d.ts(18,23): error TS7006: Parameter 'Response' implicitly has an 'any' type.
node_modules/ng2-src-directive/src/src.directive.d.ts(1,10): error TS2305: Module '"/Users/terrymooreii/code/github/ngSemantic/node_modules/@angular/core/index"' has no exported member 'AppViewManager'.

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/bin/npm" "run" "demo:build"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! ng-semantic@1.0.21 demo:build: `rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ng-semantic@1.0.21 demo:build script 'rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng-semantic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf demo/app && tslint -c ./tslint.json 'src/app/**/*.ts' && tsc -p './src' --rootDir './src' --outDir './demo' && cd src && find . -name '*.html' | cpio -pdm ../demo
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng-semantic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng-semantic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/terrymooreii/code/github/ngSemantic/npm-debug.log
```

The `ng2-src-directive` package is pulled in from ngSemantic's dependency on `ng2-prism` which is still at Angular 2 beta.  I am not sure how to work around these issues until the `ng2-prism` is updated.  Any help would be appreciated.

**Comment by jameswestnz** [comment]
I've done the same - found that everything was working but the demo, so ditched it and included ng-semantic in my project instead.

If we have solid tests in place, do we need the demo as part of this package? I'm thinking that many people will simply install through `npm` then copy and paste from your demo etc. Could even have a readme for each component that has a copy-and-paste example for users to get going.

I've added some more components myself (well, added other options such as password input type so far), so will contribute back once they're stable at our end, and you've got an RC version up here.

Let me know if you have any questions :)

**Comment by aaweb** [comment]
@vladotesanovic: Any news on this from last time? :)

**Comment by vladotesanovic** [comment]
Repository ( demo ) and library from npm are on rc.1 now.
